In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("~/Downloads/uc_all.csv")

In [3]:
data

,fullname,campus,city,fall_term,measure_name,school_name,ethcat,total_number,ceeb_id,gpa,status
0,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,adm,BELLA VISTA HIGH SCHOOL,Asian,12.0,50912,NaN,frosh
1,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,app,BELLA VISTA HIGH SCHOOL,Asian,13.0,50912,NaN,frosh
2,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,enr,BELLA VISTA HIGH SCHOOL,Hispanic/ Latino,4.0,50912,NaN,frosh
3,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,adm,BELLA VISTA HIGH SCHOOL,Hispanic/ Latino,10.0,50912,NaN,frosh
4,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,app,BELLA VISTA HIGH SCHOOL,Hispanic/ Latino,10.0,50912,NaN,frosh
...,...,...,...,...,...,...,...,...,...,...,...
2336278,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,app,BELLA VISTA HIGH SCHOOL,Domestic Unknown,9.0,50912,NaN,frosh
2336279,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,enr,BELLA VISTA HIGH SCHOOL,White,28.0,50912,NaN,frosh
2336280,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,adm,BELLA VISTA HIGH SCHOOL,White,50.0,50912,NaN,frosh
2336281,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,app,BELLA VISTA HIGH SCHOOL,White,53.0,50912,NaN,frosh
2336282,BELLA VISTA HIGH SCHOOL50912,Universitywide,Fair Oaks,2005-9-1,enr,BELLA VISTA HIGH SCHOOL,Asian,4.0,50912,NaN,frosh